file(REMOVE_RECURSE "${TEST_BINARY_DIR}")
file(MAKE_DIRECTORY "${TEST_BINARY_DIR}/provider" "${TEST_BINARY_DIR}/prefix" "${TEST_BINARY_DIR}/consumer")

execute_process(COMMAND ${CMAKE_COMMAND} -S "${PROVIDER_SOURCE_DIR}" -B "${TEST_BINARY_DIR}/provider"
  -DBUILD_TESTS=OFF -DCMAKE_INSTALL_PREFIX=${TEST_BINARY_DIR}/prefix RESULT_VARIABLE configure_result)
if(NOT configure_result EQUAL 0)
  message(FATAL_ERROR "Provider configure failed")
endif()
execute_process(COMMAND ${CMAKE_COMMAND} --build "${TEST_BINARY_DIR}/provider" RESULT_VARIABLE build_result)
if(NOT build_result EQUAL 0)
  message(FATAL_ERROR "Provider build failed")
endif()
execute_process(COMMAND ${CMAKE_COMMAND} --install "${TEST_BINARY_DIR}/provider" RESULT_VARIABLE install_result)
if(NOT install_result EQUAL 0)
  message(FATAL_ERROR "Provider install failed")
endif()
execute_process(COMMAND ${CMAKE_COMMAND} -S "${CMAKE_CURRENT_LIST_DIR}/package-consumer"
  -B "${TEST_BINARY_DIR}/consumer" -DCMAKE_PREFIX_PATH=${TEST_BINARY_DIR}/prefix RESULT_VARIABLE consumer_configure_result)
if(NOT consumer_configure_result EQUAL 0)
  message(FATAL_ERROR "Audio consumer configure failed")
endif()
execute_process(COMMAND ${CMAKE_COMMAND} --build "${TEST_BINARY_DIR}/consumer" RESULT_VARIABLE consumer_build_result)
if(NOT consumer_build_result EQUAL 0)
  message(FATAL_ERROR "Audio consumer build failed")
endif()
