cmake_minimum_required(VERSION 3.25)
project(storage-consumer LANGUAGES CXX)
set(CMAKE_DISABLE_FIND_PACKAGE_PkgConfig TRUE)
find_package(HoloNightSystemServices REQUIRED COMPONENTS Storage)
if(TARGET HoloNightSystem::Audio OR TARGET PkgConfig::LIBPULSE)
  message(FATAL_ERROR "Storage loaded Audio dependencies")
endif()
add_executable(storage-consumer main.cpp)
target_link_libraries(storage-consumer PRIVATE HoloNightSystem::Storage)
