cmake_minimum_required(VERSION 3.25)
project(audio-consumer LANGUAGES CXX)
set(CMAKE_DISABLE_FIND_PACKAGE_Qt6DBus TRUE)
find_package(HoloNightSystemServices REQUIRED)
if(TARGET HoloNightSystem::Storage OR TARGET Qt6::DBus)
  message(FATAL_ERROR "Audio loaded Storage dependencies")
endif()
add_executable(audio-consumer main.cpp)
target_link_libraries(audio-consumer PRIVATE HoloNightSystem::Audio)
